---
- hosts: web
  become: true
  tasks:
   - name: Ansible Version Check
     command: ansible --version
     register: status

   - name: displaying version of ansible
     debug:
      var: status.stdout
