- hosts: all
  become: yes
  tasks:
   - name: Update package
     apt:
        update_cache: yes
   - name: Update Apt
     command: apt update -y
     register: version
   
   - name: Printing Version
     debug: 
      var: version.stdout
   
