- hosts: all
  become: yes
  tasks:
   - name: Update package
     apt:
        update_cache: yes
   - name: Install Git
     command: apt install git -y

   - name: Install Git
     command: git --version
     register: git_version  
   
   - name: Printing Git Version
     debug: 
      var: git_version.stdout
   
