---
- hosts: all
  become: true
  tasks:
   - name: Dislaying Username
     command: whoami
     register: whoami
   - name: Display Username
     debug:
      var: whoami.stdout
   - name: Dislaying ps aux command
     command: ps aux -u ubuntu
     register: psaux
   - name: Display Username
     debug:
      var: psaux.stdout   
