---
- hosts: all
  become: true
  #become_user: ubuntu
  tasks:
   - name: Dislaying Username
     command: whoami
     register: whoami
   - name: Display Username
     debug:
      var: whoami.stdout
   - name: current working directory
     command: pwd
     register: pwd
   - name: Display Directory
     debug:
      var: pwd.stdout
